name: openfold3-env
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
dependencies:
  - python
  - awscli
  - setuptools
  - pip
  - conda-forge::uv
  - pytorch-lightning
  - biopython
  - numpy
  - pandas
  - PyYAML
  - requests
  - scipy
  - tqdm
  - typing-extensions
  - wandb
  - modelcif
  - ml-collections
  - mkl
  - rdkit=2025.09.3
  - biotite
  - mmseqs2
  - bioconda::hmmer
  - bioconda::hhsuite
  - bioconda::snakemake
  - pytorch::pytorch
  - pytorch::pytorch-cuda
  - memory_profiler
  - func_timeout
  - boto3
  - conda-forge::python-lmdb=1.6
  - conda-forge::ijson
  - pip:
      - deepspeed
      - pdbeccdutils
      - kalign-python
