experiment_settings:
  mode: train
  output_dir: ./test_train_output
  restart_checkpoint_path: last
  preemption_safe_resume: true
  ckpt_load_settings:
    manual_checkpoint_loading: true
    init_from_ema_weights: true
    restore_lr_scheduler: false
    restore_time_step: true
    strict_loading: false

data_module_args:
  batch_size: 1
  num_workers: 16
  epoch_len: 128000 # Ckpt every 500 steps

logging_config:
  log_lr : true 
  wandb_config:
    project: <project_name>
    entity: <entity_name> 
    group: null
    id: null
    experiment_name: <experiment_name> 

pl_trainer_args:
  devices: 8
  num_nodes: 32
  precision: bf16-mixed
  max_epochs: -1
  log_every_n_steps: 50
  
  mpi_plugin: false
  deepspeed_config_path: null

# Checkpoint settings
checkpoint_config:
  every_n_epochs: 1
  auto_insert_metric_name: false
  save_last: true
  save_top_k: -1

model_update:
  presets: 
    - train 
  custom:
    settings:
      train_confidence_only: true
      model_selection_weight_scheme: fine_tuning
      ema:
        submodules_to_update:
          - aux_heads.pairformer_embedding
          - aux_heads.pde
          - aux_heads.plddt
          - aux_heads.experimentally_resolved
          - aux_heads.pae
    architecture:
      heads:
        pae:
          enabled: true

dataset_configs:
  train:
    weighted-pdb:
      dataset_class: WeightedPDBDataset
      weight: 1.0
      config:
        debug_mode: true
        template:
          n_templates: 4
          take_top_k: false
        crop:
          token_crop:
            enabled: true
            token_budget: 768
            crop_weights:
              contiguous: 0.2
              spatial: 0.4
              spatial_interface: 0.4
          chain_crop:
            enabled: true
            n_chains: 50
        loss:
          loss_weights:
            mse: 0.0
            smooth_lddt: 0.0
            distogram: 0.0
            pae: 0.0001

  validation:
    val-weighted-pdb:
      dataset_class: ValidationPDBDataset
      config:
        debug_mode: true
        msa:
          subsample_main: false
        template:
          n_templates: 4
          take_top_k: true
        crop:
          token_crop:
            enabled: false

dataset_paths:
  weighted-pdb:
    alignments_directory: none 
    alignment_db_directory: none 
    alignment_array_directory: /path/ 
    dataset_cache_file: /path/ 
    target_structures_directory: /path 
    target_structure_file_format: npz
    reference_molecule_directory: /path/ 
    template_cache_directory: /path/ 
    template_structure_array_directory: /path/ 
    template_structures_directory: none
    template_file_format: npz
    ccd_file: /path 

  val-weighted-pdb:
    alignments_directory: none 
    alignment_db_directory: none 
    alignment_array_directory: /path/ 
    dataset_cache_file: /path/ 
    target_structures_directory: /path 
    target_structure_file_format: npz
    reference_molecule_directory: /path/ 
    template_cache_directory: /path/ 
    template_structure_array_directory: /path/ 
    template_structures_directory: none
    template_file_format: npz
    ccd_file: /path
